version: '3.8'

services:
  jenkins:
    build: .
    container_name: ${JENKINS_CONTAINER_NAME:-cloud4next_jenkins}
    environment:
      - JENKINS_OPTS="--prefix=${JENKINS_PREFIX:-/jenkins}"
      - JENKINS_JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    ports:
      - "${JENKINS_PORT:-8080}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge 