jenkins:
  systemMessage: "Welcome to Cloud4Next Jenkins"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 2
  labelString: "master"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "{{ jenkins_admin_password }}"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated" 